package web.mates.arriendatufinca.controller;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.NonNull;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import web.mates.arriendatufinca.model.user.dto.LoginDTO;
import web.mates.arriendatufinca.model.user.dto.SignUpDTO;
import web.mates.arriendatufinca.model.user.dto.SimpleUserDTO;
import web.mates.arriendatufinca.service.UserService;

import java.util.HashMap;
import java.util.Map;

@RestController
@RequestMapping("/auth")
@Tag(name = "Auth", description = "JWT and Security related operations")
public class AuthController {
    private final UserService userService;

    AuthController(UserService userService) {
        this.userService = userService;
    }

    @Operation(
            summary = "Sign Up",
            description = "Create a new user"
    )
    @ApiResponses(value = {
            @ApiResponse(
                    responseCode = "201",
                    description = "The user was successfully created"
            ),
            @ApiResponse(
                    responseCode = "400",
                    description = "One or more fields are not properly formatted or do not comply with current constraints. Response returns a description of which fields must be fixed",
                    content = @Content
            )
    })
    @PostMapping("/signup")
    public ResponseEntity<SimpleUserDTO> signUp(
            @Parameter(
                    description = "User object to register",
                    required = true,
                    schema = @Schema(implementation = SignUpDTO.class)
            )
            @NonNull @RequestBody @Valid SignUpDTO user
    ) {
        return new ResponseEntity<>(userService.create(user), HttpStatus.CREATED);
    }

    @Operation(
            summary = "Login",
            description = "Authenticate and retrieve JWT Token for user credentials"
    )
    @ApiResponses({
            @ApiResponse(
                    responseCode = "200",
                    content = @Content(mediaType = "application/json",
                            schema = @Schema(implementation = LoginDTO.class))
            ),
            @ApiResponse(
                    responseCode = "400",
                    description = "User has not been activated"
            ),
            @ApiResponse(
                    responseCode = "401",
                    description = "Invalid Credentials"
            ),
            @ApiResponse(
                    responseCode = "404",
                    description = "User was not found"
            )
    })
    @PostMapping("/login")
    public ResponseEntity<Map<String, String>> login(@RequestBody @Valid LoginDTO credentials) {
        String email = credentials.getEmail();
        String password = credentials.getPassword();
        String token = userService.login(email, password);
        Map<String, String> response = new HashMap<>();
        response.put("token", token);
        return new ResponseEntity<>(response, HttpStatus.OK);
    }

    @Operation(
            summary = "Verify account",
            description = "Verifies and activates an account to be used"
    )
    @ApiResponses({
            @ApiResponse(
                    responseCode = "200",
                    description = "The user was successfully activated"
            ),
            @ApiResponse(
                    responseCode = "204",
                    description = "User has already been activated"
            ),
            @ApiResponse(
                    responseCode = "404",
                    description = "User was not found"
            )
    })
    @GetMapping("/verify")
    public ResponseEntity<Void> verify(
            @Parameter(
                    description = "Code generated by sent email",
                    required = true,
                    in = ParameterIn.QUERY,
                    schema = @Schema(implementation = String.class)
            )
            @RequestParam("code") String code
    ) {
        boolean result = userService.verify(code);
        if (result)
            return new ResponseEntity<>(HttpStatus.OK);
        else
            return new ResponseEntity<>(HttpStatus.NO_CONTENT);
    }

    @Operation(
            summary = "Sends email with verification link",
            description = "Finds user with given email and sends verification link"
    )
    @ApiResponses({
             @ApiResponse(
                     responseCode = "200",
                     description = "Email was successfully sent"
             ),
            @ApiResponse(
                    responseCode = "404",
                    description = "There is no user with given email"
            ),
            @ApiResponse(
                    responseCode = "400",
                    description = "User has already been activated"
            )
    })
    @GetMapping("/requestverify")
    public ResponseEntity<Void> sendVerificationEmail(
            @Parameter(
                    name = "email",
                    description = "Email of user to be activated",
                    required = true,
                    in = ParameterIn.QUERY,
                    schema = @Schema(implementation = String.class)
            )
            @NonNull @RequestParam("email") String email
    ) {
        userService.sendVerificationEmail(email);
        return new ResponseEntity<>(HttpStatus.OK);
    }
}
